# Generated by Django 4.1.3 on 2022-12-10 20:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_customusermodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
