# Generated by Django 4.1.4 on 2022-12-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='Rasm',
            field=models.ImageField(blank=True, help_text='Article Image', null=True, unique=True, upload_to='images/articles/'),
        ),
    ]
