# Generated by Django 4.1.4 on 2022-12-11 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_articlemodel_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='Yangi Sana',
            field=models.DateTimeField(auto_now=True, help_text="Ohirgi o'zgartirilgan sana"),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='Yaratilgan Sana',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Yaratilgan Sana'),
            preserve_default=False,
        ),
    ]
