# Generated by Django 4.1.4 on 2022-12-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_articlemodel_yangi sana_articlemodel_yaratilgan sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='Slug',
            field=models.SlugField(default=1, help_text='Takrorlanmas Nom', unique=True),
            preserve_default=False,
        ),
    ]
