# Generated by Django 4.1.4 on 2022-12-11 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Articles', '0004_articlemodel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='Yangi Sana',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='Yaratilgan Sana',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='author',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='Author',
            field=models.ForeignKey(default=1, help_text='Article Author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
