# Generated by Django 4.1.4 on 2022-12-11 15:16

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_rename_title_articlemodel_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='Article Content Text',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1),
            preserve_default=False,
        ),
    ]
