# Generated by Django 4.1.4 on 2022-12-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0007_remove_articlemodel_author_remove_articlemodel_rasm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='Ega',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='articlemodel',
            old_name='RASIM_UZ',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='articlemodel',
            old_name='TAKRORLANMASI_NOM',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='SARLAVHA',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(default=1, help_text='MAQOLA SARLAVHA', max_length=256),
            preserve_default=False,
        ),
    ]
