# Generated by Django 4.1.4 on 2022-12-11 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Articles', '0008_rename_ega_articlemodel_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='author',
            field=models.ForeignKey(help_text='Article Author UZ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='image',
            field=models.ImageField(blank=True, help_text='Article Image UZ', null=True, unique=True, upload_to='images/articles/'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='slug',
            field=models.SlugField(help_text='Takrorlanmas Nom UZ', unique=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(help_text='Article Title UZ', max_length=256),
        ),
    ]
