# Generated by Django 4.1.4 on 2022-12-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0010_alter_articlemodel_author_alter_articlemodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='articles_images/'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
