# Generated by Django 4.1.4 on 2022-12-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0012_alter_articlemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='is_check',
            field=models.BooleanField(default=True),
        ),
    ]
