# Generated by Django 4.1.4 on 2022-12-12 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Articles', '0013_articlemodel_is_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='like',
            field=models.ManyToManyField(related_name='article_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
