# Generated by Django 4.1.4 on 2022-12-12 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Articles', '0014_articlemodel_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='like',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='likes',
            field=models.ManyToManyField(related_name='article_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
