# Generated by Django 4.1.4 on 2022-12-13 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Articles', '0016_alter_articlemodel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='article_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
