# Generated by Django 4.1.4 on 2022-12-12 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Articles', '0012_alter_articlemodel_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=256)),
                ('created_cm', models.DateTimeField(auto_now_add=True)),
                ('updated_cm', models.DateTimeField(auto_now=True)),
                ('is_check', models.BooleanField(default=True)),
                ('article_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.articlemodel')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
