# Generated by Django 4.1.4 on 2022-12-12 10:06

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=256),
        ),
    ]
