# Generated by Django 4.1.4 on 2022-12-12 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0014_articlemodel_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comments', '0002_alter_commentmodel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='like',
            field=models.ManyToManyField(related_name='comment_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='article_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='Articles.articlemodel'),
        ),
    ]
