# Generated by Django 4.1.4 on 2022-12-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0004_remove_commentmodel_like_commentmodel_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='likes',
        ),
    ]
