# Generated by Django 4.1.4 on 2022-12-12 14:47

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0005_remove_commentmodel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=256, null=True),
        ),
    ]
