# Generated by Django 4.1.4 on 2022-12-12 14:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Articles', '0016_alter_articlemodel_likes'),
        ('Comments', '0006_alter_commentmodel_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentModel',
            new_name='CommentArticle',
        ),
    ]
