# Generated by Django 4.1.4 on 2022-12-13 06:20

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0007_rename_commentmodel_commentarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarticle',
            name='comment',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
