# Generated by Django 4.1.3 on 2022-12-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_alter_profile_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='profile_pics/'),
        ),
    ]
