# Generated by Django 4.1.4 on 2022-12-12 14:30

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_alter_profile_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=500, null=True),
        ),
    ]
