name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      


    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Test
        env:
          SECRET_KEY: CI_CD_TEST_KEY
          EMAIL_HOST_USER: test@gmail.com
          EMAIL_HOST_PASSWORD: email_password
        run: |
          python manage.py test

      - name: Test CollectStatic
        env:
          SECRET_KEY: CI_CD_TEST_KEY
          EMAIL_HOST_USER: test@gmail.com
          EMAIL_HOST_PASSWORD: email_password
        run: |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py collectstatic


      
